### ISSUE TITLE
Kernel always died at step of BASE_VECTORS = get_features(data_processed)

### ISSUE THREAD

**Issue by zhezhe123** [NISH1001/machine-learning-into-the-void#1]
Kernel always died at the step of BASE_VECTORS = get_features(data_processed).

**Comment by NISH1001** [comment]
Hi @zhezhe123 ,
What was the size of the data you were trying to process? The kernel may have died if there is resource exhaustion. I had faced similar issues with huge data.

**Comment by zhezhe123** [comment]
Original data set is 850k, reduce to 5k, works fine. Looks like it's the data size issue. Thanks a lot!
